CREATE DATABASE DW

USE DW

-- CARGA DAS DIMENSOES --> SO INSERIR NOVOS REGISTROS DAS TABELAS DIM
-- DIM_CARROCERIA
INSERT INTO DIM_CARROCERIA
SELECT * FROM STAGING..DIM_CARROCERIA
WHERE id_carroceria NOT IN (SELECT id_carroceria FROM DIM_CARROCERIA) -- (..)OPCIONAL

-- DIM_COMBUSTIVEL
INSERT INTO DIM_COMBUSTIVEL
SELECT * FROM STAGING..DIM_COMBUSTIVEL
WHERE id_combustivel NOT IN (SELECT id_combustivel FROM DIM_COMBUSTIVEL)

-- DIM_DATA
INSERT INTO DIM_DATA
SELECT * FROM STAGING..DIM_DATA
WHERE id_data NOT IN (SELECT id_data FROM DIM_DATA

-- DIM_MODELO
INSERT INTO DIM_MMODELO
SELECT * FROM STAGING..DIM_MMODELO
WHERE id_mmodelo NOT IN (SELECT id_mmodelo FROM DIM_MMODELO)

-- DIM_MUNICIPIO
INSERT INTO DIM_MUNICIPIO
SELECT * FROM STAGING..DIM_MUNICIPIO
WHERE id_municipio NOT IN (SELECT id_municipio FROM DIM_MUNICIPIO)

-- DIM_NLUGARES
INSERT INTO DIM_NLUGARES
SELECT * FROM STAGING..DIM_NLUGARES
WHERE id_nlugares NOT IN (SELECT id_nlugares FROM DIM_NLUGARES)

-- DIM_RESTRICAO
INSERT INTO DIM_RESTRICAO
SELECT * FROM STAGING..DIM_RESTRICAO
WHERE id_restricao NOT IN (SELECT id_restricao FROM DIM_RESTRICAO)

-- FATO_LICENCIAMENTO
INSERT INTO FATO_LICENCIAMENTO
SELECT * FROM STAGING..FATO_LICENCIAMENTO
WHERE id_licenciamento NOT IN (SELECT id_licenciamento FROM DIM_RESTRICAO)