USE [STAGING]
GO
/****** Object:  Table [dbo].[carroceria]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[carroceria](
	[cod_carroceria] [varchar](3) NULL,
	[tipo_carroceria] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[combustivel]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[combustivel](
	[cod_combustivel] [varchar](3) NULL,
	[tipo_combustivel] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIARIO]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIARIO](
	[ano] [varchar](4) NULL,
	[mes] [varchar](2) NULL,
	[dia] [varchar](2) NULL,
	[cod_municipio] [varchar](4) NULL,
	[cod_mmodelo] [varchar](6) NULL,
	[ano_fabric] [varchar](4) NULL,
	[qt_licenciada] [varchar](6) NULL,
	[cilindradas] [varchar](4) NULL,
	[potencia] [varchar](3) NULL,
	[cod_combustivel] [varchar](2) NULL,
	[cod_carroceria] [varchar](3) NULL,
	[r1] [varchar](2) NULL,
	[r2] [varchar](2) NULL,
	[r3] [varchar](2) NULL,
	[r4] [varchar](2) NULL,
	[num_lugares] [varchar](3) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_CARROCERIA]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_CARROCERIA](
	[id_carroceria] [nchar](3) NOT NULL,
	[tipo_carroceria] [nchar](50) NULL,
 CONSTRAINT [PK_DIM_CARROCERIA] PRIMARY KEY CLUSTERED 
(
	[id_carroceria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_COMBUSTIVEL]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_COMBUSTIVEL](
	[id_combustivel] [nchar](3) NOT NULL,
	[combustivel] [nchar](20) NULL,
 CONSTRAINT [PK_DIM_COMBUSTIVEL] PRIMARY KEY CLUSTERED 
(
	[id_combustivel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_DATA]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_DATA](
	[id_data] [smalldatetime] NOT NULL,
	[dia] [char](2) NULL,
	[mes] [nchar](15) NULL,
	[ano] [char](4) NULL,
	[dia_semana] [nchar](25) NULL,
	[semestre] [nchar](15) NULL,
 CONSTRAINT [PK_DIM_DATA] PRIMARY KEY CLUSTERED 
(
	[id_data] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_MMODELO]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_MMODELO](
	[id_mmodelo] [nchar](6) NOT NULL,
	[marca] [nchar](40) NULL,
	[modelo] [nchar](40) NULL,
 CONSTRAINT [PK_DIM_MMODELO] PRIMARY KEY CLUSTERED 
(
	[id_mmodelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_MUNICIPIO]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_MUNICIPIO](
	[id_municipio] [nchar](4) NOT NULL,
	[municipio] [nchar](60) NULL,
	[estado] [nchar](2) NULL,
	[regiao] [nchar](20) NULL,
 CONSTRAINT [PK_DIM_MUNICIPIO] PRIMARY KEY CLUSTERED 
(
	[id_municipio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_NLUGARES]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_NLUGARES](
	[id_nlugares] [nchar](2) NOT NULL,
	[num_lugares] [nchar](20) NULL,
 CONSTRAINT [PK_DIM_NLUGARES] PRIMARY KEY CLUSTERED 
(
	[id_nlugares] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_RESTRICAO]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_RESTRICAO](
	[id_restricao] [nchar](1) NOT NULL,
	[restricao] [nchar](3) NULL,
 CONSTRAINT [PK_DIM_RESTRICAO] PRIMARY KEY CLUSTERED 
(
	[id_restricao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FATO_LICENCIAMENTO]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FATO_LICENCIAMENTO](
	[id_licenciamento] [varchar](50) NOT NULL,
	[qt_licenciada] [int] NULL,
	[id_data] [smalldatetime] NULL,
	[id_mmodelo] [nchar](6) NULL,
	[id_carroceria] [nchar](3) NULL,
	[id_municipio] [nchar](4) NULL,
	[id_combustivel] [nchar](3) NULL,
	[id_ralienado] [nchar](1) NULL,
	[id_rfinanciado] [nchar](1) NULL,
	[id_rcircproibida] [nchar](1) NULL,
	[id_rusoservico] [nchar](1) NULL,
	[id_risento] [nchar](1) NULL,
	[id_nlugares] [nchar](2) NULL,
 CONSTRAINT [PK_FATO_LICENCIAMENTO] PRIMARY KEY CLUSTERED 
(
	[id_licenciamento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[modelo]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[modelo](
	[cod_mmodelo] [varchar](6) NULL,
	[desc_mmodelo] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[municipios]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[municipios](
	[cod_municipio] [nvarchar](50) NULL,
	[nome_municipio] [nvarchar](50) NULL,
	[estado] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[restricoes]    Script Date: 15/05/2023 11:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[restricoes](
	[cod_restricao] [varchar](2) NULL,
	[tipo_restricao] [varchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_CARROCERIA] FOREIGN KEY([id_carroceria])
REFERENCES [dbo].[DIM_CARROCERIA] ([id_carroceria])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_CARROCERIA]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_COMBUSTIVEL] FOREIGN KEY([id_combustivel])
REFERENCES [dbo].[DIM_COMBUSTIVEL] ([id_combustivel])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_COMBUSTIVEL]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_DATA] FOREIGN KEY([id_data])
REFERENCES [dbo].[DIM_DATA] ([id_data])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_DATA]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_MMODELO] FOREIGN KEY([id_mmodelo])
REFERENCES [dbo].[DIM_MMODELO] ([id_mmodelo])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_MMODELO]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_MUNICIPIO] FOREIGN KEY([id_municipio])
REFERENCES [dbo].[DIM_MUNICIPIO] ([id_municipio])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_MUNICIPIO]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_NLUGARES] FOREIGN KEY([id_nlugares])
REFERENCES [dbo].[DIM_NLUGARES] ([id_nlugares])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_NLUGARES]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO] FOREIGN KEY([id_ralienado])
REFERENCES [dbo].[DIM_RESTRICAO] ([id_restricao])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO1] FOREIGN KEY([id_rfinanciado])
REFERENCES [dbo].[DIM_RESTRICAO] ([id_restricao])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO1]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO2] FOREIGN KEY([id_rcircproibida])
REFERENCES [dbo].[DIM_RESTRICAO] ([id_restricao])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO2]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO3] FOREIGN KEY([id_rusoservico])
REFERENCES [dbo].[DIM_RESTRICAO] ([id_restricao])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO3]
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO4] FOREIGN KEY([id_risento])
REFERENCES [dbo].[DIM_RESTRICAO] ([id_restricao])
GO
ALTER TABLE [dbo].[FATO_LICENCIAMENTO] CHECK CONSTRAINT [FK_FATO_LICENCIAMENTO_DIM_RESTRICAO4]
GO
