-- MUDANÇA DO PROPRIETÁRIO DO BANCO DE DADOS PARA QUANDO ATACHAR MUDARMOS DE MÁQUINA

--use <BANCO>
--exec sp_changedbowner '<USUARIO_DA_SUA_MAQUINA>'
USE STAGING
EXEC sp_changedbowner 'DYANNA\dyann'